#ifndef GRAPHICS_H
#define GRAPHICS_H
#include <ncurses.h>

enum {
	COLOR_PAIR_DEFAULT = 1,
	COLOR_PAIR_CURSOR,
	COLOR_PAIR_MINE,
	COLOR_PAIR_FLAG,
	COLOR_PAIR_1,
	COLOR_PAIR_2,
	COLOR_PAIR_3,
	COLOR_PAIR_4,
	COLOR_PAIR_5,
	COLOR_PAIR_6,
	COLOR_PAIR_7,
	COLOR_PAIR_8,
	COLOR_PAIR_ADVENTURE_EXIT,
	COLOR_PAIR_ADVENTURE_PLAYER
};

enum {
	CHAR_MINE = '*',
	CHAR_ADVENTURE_EXIT = '>',
	CHAR_ADVENTURE_PLAYER = '@',
	CHAR_FLAG = 'F',
	CHAR_TILE = '#',
	CHAR_EMPTY = ' '
};

void init_colors() {
	use_default_colors();
	init_pair(COLOR_PAIR_DEFAULT, -1, -1);
	init_pair(COLOR_PAIR_CURSOR, -1, COLOR_GREEN);
	init_pair(COLOR_PAIR_MINE, -1, COLOR_RED);
	init_pair(COLOR_PAIR_FLAG, COLOR_WHITE, COLOR_YELLOW);
	init_pair(COLOR_PAIR_1, COLOR_BLUE, -1);
	init_pair(COLOR_PAIR_2, COLOR_GREEN, -1);
	init_pair(COLOR_PAIR_3, COLOR_RED, -1);
	init_pair(COLOR_PAIR_4, COLOR_YELLOW, -1);
	// TODO: Set colors for 5,6,7,8
	init_pair(COLOR_PAIR_ADVENTURE_EXIT, COLOR_BLACK, COLOR_GREEN);
	init_pair(COLOR_PAIR_ADVENTURE_PLAYER, COLOR_GREEN, -1);
}

#endif
